---
- name: Ensure deps are installed
  apt: 
    name: ["apt-transport-https"]
    state: present
  become: yes
  become_method: sudo
  tags:
    - k8s

- name: Add Kubernates apt key.
  apt_key:
    url: "https://packages.cloud.google.com/apt/doc/apt-key.gpg"
    id: 54A647F9048D5688D7DA2ABE6A030B21BA07F4FB
    state: present
  register: add_repository_key
  become: yes
  become_method: sudo
  tags:
    - k8s

- name: Add Kubernetes repository.
  vars:
    arch: amd64
    release_channel: stable
    repository: "deb [arch=amd64] https://apt.kubernetes.io/ {{distro[ansible_distribution | lower] }} main"
  apt_repository: repo: "{{ repository }}"
    state: present
  become: yes
  become_method: sudo
  tags:
    - k8s

- name: Install kubernates
  apt:
    update_cache: yes
    name: ["kubectl", "kubeadm", "kubectl"]
    state: present
  become: yes
  become_method: sudo
  tags:
    - k8s
