---
- hosts: ocean
  user: root
  vars:
    username: sebas
    password: supersecret
    public_key: ~/.ssh/id_ed25519.pub
    ssh_port: 22
    dotfiles: /home/{{ username }}/.dotfiles
  roles:
    - common
    - sshd
