---
- name: Ensure sudo group is present
  group:
    name: sudo
    state: present

- name: Ensure sudo group has sudo priveleges
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: "^%sudo"
    line: "%sudo ALL=(ALL:ALL) ALL"
    validate: "/usr/sbin/visudo -cf %s"

- name: Create default user
  user:
    name: "{{ username }}"
    password: "{{ password }}"
    shell: /bin/zsh
    update_password: always
    state: present

- name: Add authorized key
  authorized_key:
    user: "{{ username }}"
    key: "{{lookup('file', public_key) }}"
