---
- name: Clone dotfiles
  git:
    repo: https://gitlab.com/sebohe/dotfiles 
    dest: "{{ dotfiles }}"
    force: yes
  become: yes
  become_user: "{{ username }}"

- name: Remove .bashrc
  file: 
    path: "/home/{{ username }}/.bashrc"
    state: absent

- name: Stow files
  command: "stow --target=/home/{{ username }} {{ item }}"
  args:
    chdir: "{{ dotfiles }}"
  with_items:
    - stow
    - zsh
    - bash
    - nvim
    - vim
    - tmux
    - git
  become: yes
  become_user: "{{ username }}"

