# To generate password hashes
# python -c "from passlib.hash import sha512_crypt; import getpass; print(sha512_crypt.using(rounds=5000).hash(getpass.getpass()))"
---
- hosts: cosmos
  remote_user: sebas
  vars:
    username: sebas
  roles:
    - common
    - user
    - dotfiles
    - ohmyzsh
    - sshd
    - docker-install
    - go
    - k8-install
