---
- name: Install packages
  apt:
    name: ['python3-pip',
          'python-pip',
          'zsh',
          'ufw',
          'vim',
          'neovim-runtime',
          'curl',
          'nmap',
          'ncdu',
          'git',
          'tmux',
          ]
    state: present
    update_cache: yes
  tags:
    - needed

- name: Upgrade packages
  apt: upgrade=safe
  tags:
    - needed
  
