# To generate password hashes
# python -c "from passlib.hash import sha512_crypt; import getpass; print(sha512_crypt.using(rounds=5000).hash(getpass.getpass()))"
---
- name: Ensure sudo group is present
  group:
    name: sudo
    state: present
  become: yes
  become_method: sudo
  tags:
    - user

- name: Ensure sudo group has sudo priveleges
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: "^%sudo"
    line: "%sudo ALL=(ALL:ALL) ALL"
    validate: "/usr/sbin/visudo -cf %s"
  become: yes
  become_method: sudo
  tags:
    - user

- name: Create {{ username }} user
  user:
    name: "{{ username }}"
    groups: sudo
    password: "{{ password }}"
    shell: /bin/zsh
    state: present
  become: yes
  become_method: sudo
  tags:
    - user

- name: Add authorized key
  authorized_key:
    user: "{{ username }}"
    key: "{{lookup('file', public_key) }}"
  become: yes
  become_method: sudo
  tags:
    - user
