---
- name: Ensure sudo group is present
  group:
    name: sudo
    state: present
  tags:
    - needed

- name: Ensure sudo group has sudo priveleges
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: "^%sudo"
    line: "%sudo ALL=(ALL:ALL) ALL"
    validate: "/usr/sbin/visudo -cf %s"
  tags:
    - needed

- name: Create {{ username }} user
  user:
    name: "{{ username }}"
    groups: sudo
    password: "{{ password }}"
    shell: /bin/zsh
    state: present
  tags:
    - needed

- name: Add authorized key
  authorized_key:
    user: "{{ username }}"
    key: "{{lookup('file', public_key) }}"
  tags:
    - needed
