# To generate password hashes
# python -c "from passlib.hash import sha512_crypt; import getpass; print(sha512_crypt.using(rounds=5000).hash(getpass.getpass()))"
---
- name: Ensure sudo group is present
  group:
    name: sudo
    state: present
  become: yes
  become_method: sudo
  tags:
    - user

- name: Ensure sudo group has sudo priveleges
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: "^%sudo"
    line: "%sudo ALL=(ALL:ALL) ALL"
    validate: "/usr/sbin/visudo -cf %s"
  become: yes
  become_method: sudo
  tags:
    - user

- name: Create {{ username }} user
  user:
    name: "{{ username }}"
    groups: sudo
    password: "{{ password }}"
    shell: /bin/zsh
    state: present
  become: yes
  become_method: sudo
  tags:
    - user

- name: Add authorized key
  authorized_key:
    user: "{{ username }}"
    key: "{{lookup('file', public_key) }}"
  become: yes
  become_method: sudo
  tags:
    - user

- name: Ensure zsh is the default shell
  user:
    name: "{{ username }}"
    shell: /bin/zsh
    state: present
  become: yes
  become_user: "{{username}}"
  tags:
    - dotfiles

- name: Clone dotfiles
  git:
    repo: https://gitlab.com/sebohe/dotfiles 
    dest: "{{ dotfiles }}"
    force: yes
    recursive: yes
  become: yes
  become_user: "{{ username }}"
  tags:
    - dotfiles

- name: Create directories
  file:
    state: directory
    path: "{{ item }}"
  with_items: "{{dirs}}"
  become: yes
  become_user: "{{ username }}"
  tags:
    - dotfiles

- name: Link dotfiles
  file:
    path: "~/{{ item }}"
    src: "{{ dotfiles }}/{{ item }}"
    state: link
    force: yes
  with_items: "{{ server }}"
  become: yes
  become_user: "{{ username }}"
  tags:
    - dotfiles

- name: Cloning oh-my-zsh
  git:
    repo: https://github.com/robbyrussell/oh-my-zsh
    dest: "/home/{{ username }}/.oh-my-zsh"
    force: yes
  become: yes
  become_user: "{{ username }}"
  tags:
    - dotfiles

- name: Create directories
  file:
    state: directory
    path: "~/.oh-my-zsh/custom/themes"
  become: yes
  become_user: "{{ username }}"
  tags:
    - dotfiles

- name: Link dotfiles
  file:
    path: "~/.oh-my-zsh/custom/themes/oxide.zsh-theme"
    src: "{{ dotfiles }}/.oh-my-zsh/custom/themes/oxide.zsh-theme"
    state: link
    force: yes
  become: yes
  become_user: "{{ username }}"
  tags:
    - dotfiles
