---
- name: Clone dotfiles
  git:
    repo: https://gitlab.com/sebohe/dotfiles 
    dest: "{{ dotfiles }}"
    force: yes
    recursive: yes
  become: yes
  become_user: "{{ username }}"
  tags:
    - dotfiles

- name: Remove .bashrc
  file:
    path: "/home/{{ username }}/.bashrc"
    state: absent
  tags:
    - dotfiles

- name: Create directories
  file:
    state: directory
    path: "{{ item }}"
  with_items: "{{dirs}}"
  become: yes
  become_user: "{{ username }}"
  tags:
    - dotfiles

- name: Link dotfiles
  file:
    path: "~/{{ item }}"
    src: "{{ dotfiles }}/{{ item }}"
    state: link
    force: yes
  with_items: "{{ server }}"
  become: yes
  become_user: "{{ username }}"
  tags:
    - dotfiles
