---
- name: Cloning oh-my-zsh
  git:
    repo: https://github.com/robbyrussell/oh-my-zsh
    dest: "/home/{{ username }}/.oh-my-zsh"
    force: yes
  become: yes
  become_user: "{{ username }}"
  tags:
    - dotfiles

- name: Create directories
  file:
    state: directory
    path: "~/.oh-my-zsh/custom/themes"
  become: yes
  become_user: "{{ username }}"
  tags:
    - dotfiles

- name: Link dotfiles
  file:
    path: "~/.oh-my-zsh/custom/themes/oxide.zsh-theme"
    src: "{{ dotfiles }}/.oh-my-zsh/custom/themes/oxide.zsh-theme"
    state: link
    force: yes
  become: yes
  become_user: "{{ username }}"
  tags:
    - dotfiles
