# Don't print a new line at the start of the prompt
add_newline = true

[aws]
format = 'on [$symbol($profile )(\($region\) )]($style)'

# Replace the "❯" symbol in the prompt with "➜"
[character]      # The name of the module we are confguring is "character"
success_symbol = "[➜](bold green)"     # The "symbol" segment is being set to "➜"
error_symbol = "[➜](bold red)"     # The "symbol" segment is being set to "➜"

[directory]
style = "bold blue"

[cmd_duration]
disabled = true
