---
- name: Ensure deps are installed
  apt: 
    name: "{{ item }}"
    state: present
  with_items:
    - apt-transport-https
    - ca-certificates

- name: Add Docker apt key.
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    state: present
  register: add_repository_key

- name: Install docker
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: present
  with_items:
    - docker-ce

- name: Enable docker systemd service
  service:
    name: docker
    state: restarted 
    enabled: yes

- name: Add {{ username }} to docker user group
  shell: usermod -aG docker {{username}}
